learn_templates/app_bs/urls.py
from django.urls import path
from app_bs import views

app_name = 'app_bs'

urlpatterns=[
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from app_bs import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('app_bs/', include('app_bs.urls')),
]

learn_templates/app_bs/models.py
from django.db import models

# Create your models here.

learn_templates/app_bs/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict={'text':'Hello World', 'number':100}
    return render(request, 'app_bs/index.html', context_dict)

def other(request):
    return render(request, 'app_bs/other.html')

def relative(request):
    return render(request, 'app_bs/relative_url.html')

learn_templates/templates/app_bs/base.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
          
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_bs:other' %}">Other</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}

        </div>
    </body>
</html>

learn_templates/templates/app_bs/index.html
<!DOCTYPE html>
{% extends "app_bs/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO INDEX!!</h1>
        <h2>{{ text|cut:'World'}}</h2>
        <h2>{{ number }}</h2>
    {% endblock %}
    

learn_templates/templates/app_bs/other.html
<!DOCTYPE html>
{% extends "app_bs/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO OTHER!!</h1>
        <h2>This the example of template inheritance</h2>
    {% endblock %}
   

learn_templates/templates/app_bs/relative_url.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1>WELCOME TO RELATIVE URL</h1>

        <a href="{% url 'app_bs:other' %}">LINK TO OTHER</a>
        <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
        <a href="{% url 'index' %}">LINK YO INDEX</a>
    </body>
</html>